apiVersion: v1
kind: Pod
metadata:
  name: tomcat-app
  labels:
    app: tomcat-buddy
spec:
  containers:
  - name: tomcat-appp
    image: rajesh1718/practice:app
    ports:
    - containerPort: 8080
